/**
 * Stellar/Soroban contract addresses and known assets.
 *
 * Design principles:
 * - Each protocol has its own typed interface — no more generic `Record<string, unknown>` casts
 * - Separate concerns: protocol contracts, asset definitions, pool lists
 * - Network-keyed maps for easy per-network lookup
 *
 * Moved from apps/mcp-stellar/src/config/contracts.ts
 */

import type { StellarNetwork } from "../types/common.js";

// ─── Per-protocol contract interfaces ────────────────────────────

export interface BlendContracts {
  backstop: string;
  poolFactory: string;
  emitter: string;
  blndToken: string;
  usdcToken: string;
  cometLpPool: string;
  cometFactory: string;
  /** Known named pools (dynamic discovery via backstop rewardZone is preferred) */
  knownPools: ReadonlyArray<{ name: string; address: string }>;
}

export interface SoroswapContracts {
  router: string;
  factory?: string;
}

export interface AquariusContracts {
  router: string;
  aquaToken: string;
  /**
   * Testnet: Aquarius uses a different USDC contract than the canonical Circle testnet USDC.
   * When set, the Aquarius adapter substitutes this address for the network's default USDC.
   */
  usdcOverride?: string;
}

export interface PhoenixContracts {
  factory: string;
  multihop: string;
  phoToken: string;
  /** Pre-mapped pool addresses for gas-free discovery */
  knownPools: ReadonlyArray<{
    address: string;
    stake: string;
    tokens: [string, string];
  }>;
}

export interface DefindexContracts {
  factory: string;
  /**
   * Testnet: factory address is wrong (copy-paste from Blend).
   * Use these hardcoded vaults instead.
   */
  knownVaults?: ReadonlyArray<{ name: string; address: string; asset: string }>;
}

export interface TokenContracts {
  /** Native XLM SAC (standard on Soroban) */
  xlmSac: string;
  /** XLM SAC as used by Soroswap aggregator (different on mainnet) */
  xlmSacSoroswap: string;
  usdc: string;
}

// ─── Mainnet contracts ────────────────────────────────────────────

const MAINNET_TOKENS: TokenContracts = {
  xlmSac: "CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA",
  xlmSacSoroswap: "CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA",
  usdc: "CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75",
};

const MAINNET_BLEND: BlendContracts = {
  backstop: "CAQQR5SWBXKIGZKPBZDH3KM5GQ5GUTPKB7JAFCINLZBC5WXPJKRG3IM7",
  poolFactory: "CDSYOAVXFY7SM5S64IZPPPYB4GVGGLMQVFREPSQQEZVIWXX5R23G4QSU",
  emitter: "CCOQM6S7ICIUWA225O5PSJWUBEMXGFSSW2PQFO6FP4DQEKMS5DASRGRR",
  blndToken: "CD25MNVTZDL4Y3XBCPCJXGXATV5WUHHOWMYFF4YBEGU5FCPGMYTVG5JY",
  usdcToken: "CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75",
  cometLpPool: "CAS3FL6TLZKDGGSISDBWGGPXT3NRR4DYTZD7YOD3HMYO6LTJUVGRVEAM",
  cometFactory: "CA2LVIPU6HJHHPPD6EDDYJTV2QEUBPGOAVJ4VIYNTMFUCRM4LFK3TJKF",
  knownPools: [
    { name: "Fixed Pool",     address: "CAJJZSGMMM3PD7N33TAPHGBUGTB43OC73HVIK2L2G6BNGGGYOSSYBXBD" },
    { name: "Orbit Pool",     address: "CAE7QVOMBLZ53CDRGK3UNRRHG5EZ5NQA7HHTFASEMYBWHG6MDFZTYHXC" },
    { name: "YieldBlox Pool", address: "CCCCIQSDILITHMM7PBSLVDT5MISSY7R26MNZXCX4H7J5JQ5FPIYOGYFS" },
    { name: "Etherfuse Pool", address: "CDMAVJPFXPADND3YRL4BSM3AKZWCTFMX27GLLXCML3PD62HEQS5FPVAI" },
    { name: "Forex Pool",     address: "CBYOBT7ZCCLQCBUYYIABZLSEGDPEUWXCUXQTZYOG3YBDR7U357D5ZIRF" },
  ],
};

const MAINNET_SOROSWAP: SoroswapContracts = {
  router: "CAG5LRYQ5JVEUI5TEID72EYOVX44TTUJT5BQR2J6J77FH65PCCFAJDDH",
};

const MAINNET_AQUARIUS: AquariusContracts = {
  router: "CBQDHNBFBZYE4MKPWBSJOPIYLW4SFSXAXUTSXJN76GNKYVYPCKWC6QUK",
  aquaToken: "CAUIKL3IYGMERDRUN6YSCLWVAKIFG5Q4YJHUKM4S4NJZQIA3BAS6OJPK",
};

const MAINNET_PHOENIX: PhoenixContracts = {
  factory: "CB4SVAWJA6TSRNOJZ7W2AWFW46D5VR4ZMFZKDIKXEINZCZEGZCJZCKMI",
  multihop: "CCLZRD4E72T7JCZCN3P7KNPYNXFYKQCL64ECLX7WP5GNVYPYJGU2IO2G",
  phoToken: "CBZ7M5B3Y4WWBZ5XK5UZCAFOEZ23KSSZXYECYX3IXM6E2JOLQC52DK32",
  knownPools: [
    { address: "CBHCRSVX3ZZ7EGTSYMKPEFGZNWRVCSESQR3UABET4MIW52N4EVU6BIZX", stake: "CAF3UJ45ZQJP6USFUIMVMGOUETUTXEC35R2247VJYIVQBGKTKBZKNBJ3", tokens: ["XLM", "USDC"] },
    { address: "CD5XNKK3B6BEF2N7ULNHHGAMOKZ7P6456BFNIHRF4WNTEDKBRWAE7IAA", stake: "CDOXQONPND365K6MHR3QBSVVTC3MKR44ORK6TI2GQXUXGGAS5SNDAYRI", tokens: ["PHO", "USDC"] },
    { address: "CBCZGGNOEUZG4CAAE7TGTQQHETZMKUT4OIPFHHPKEUX46U4KXBBZ3GLH", stake: "CBRGNWGAC25CPLMOAMR7WBPOF5QTFA5RYXQH4DEJ4K65G2QFLTLMW7RO", tokens: ["XLM", "PHO"] },
    { address: "CBISULYO5ZGS32WTNCBMEFCNKNSLFXCQ4Z3XHVDP4X4FLPSEALGSY3PS", stake: "CDEQYRWFU3IHPRR6H6VOQRUU3JFS6DTUYUL4YAQSD3ALB5IPBTEOZUFM", tokens: ["XLM", "EURC"] },
  ],
};

const MAINNET_DEFINDEX: DefindexContracts = {
  factory: "CDKFHFJIET3A73A2YN4KV7NSV32S6YGQMUFH3DNJXLBWL4SKEGVRNFKI",
};

// ─── Testnet contracts ────────────────────────────────────────────

const TESTNET_TOKENS: TokenContracts = {
  xlmSac: "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC",
  xlmSacSoroswap: "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC",
  // Aquarius testnet USDC (issuer GAHPYWLK...) — has actual SDEX/Aquarius liquidity
  usdc: "CAZRY5GSFBFXD7H6GAFBA5YGYQTDXU4QKWKMYFWBAZFUCURN3WKX6LF5",
};

const TESTNET_BLEND: BlendContracts = {
  backstop: "CBDVWXT433PRVTUNM56C3JREF3HIZHRBA64NB2C3B2UNCKIS65ZYCLZA",
  poolFactory: "CDSCWE4GLNBYYTES2OCYDFQA2LLY4RBIAX6ZI32VSUXD7GO6HRPO4A32",
  emitter: "CC3WJVJINN4E3LPMNTWKK7LQZLYDQMZHZA7EZGXATPHHBPKNZRIO3KZ6",
  blndToken: "CB22KRA3YZVCNCQI64JQ5WE7UY2VAV7WFLK6A2JN3HEX56T2EDAFO7QF",
  usdcToken: "CAQCFVLOBK5GIULPNZRGATJJMIZL5BSP7X5YJVMGCPTUEPFM4AVSRCJU",
  cometLpPool: "CA5UTUUPHYL5K22UBRUVC37EARZUGYOSGK3IKIXG2JLCC5ZZLI4BDWDM",
  cometFactory: "CDX2TKELFKHP2MWISDCXWWZ73CL7F57GHYRJAWJWNOTLNJNNM7XLT4JY",
  knownPools: [
    { name: "TestnetV2 Pool", address: "CCEBVDYM32YNYCVNRXQKDFFPISJJCV557CDZEIRBEE4NCV4KHPQ44HGF" },
  ],
};

const TESTNET_SOROSWAP: SoroswapContracts = {
  router: "CCJUD55AG6W5HAI5LRVNKAE5WDP5XGZBUDS5WNTIVDU7O264UZZE7BRD",
  factory: "CDP3HMUH6SMS3S7NPGNDJLULCOXXEPSHY4JKUKMBNQMATHDHWXRRJTBY",
};

const TESTNET_AQUARIUS: AquariusContracts = {
  router: "CBCFTQSPDBAIZ6R6PJQKSQWKNKWH2QIV3I4J72SHWBIK3ADRRAM5A6GD",
  aquaToken: "CAUIKL3IYGMERDRUN6YSCLWVAKIFG5Q4YJHUKM4S4NJZQIA3BAS6OJPK",
  // Aquarius testnet uses a different USDC contract than the canonical Circle testnet USDC
  usdcOverride: "CAZRY5GSFBFXD7H6GAFBA5YGYQTDXU4QKWKMYFWBAZFUCURN3WKX6LF5",
};

const TESTNET_PHOENIX: PhoenixContracts = {
  // NOTE: Phoenix testnet is redeployed each run; using mainnet addresses as fallback
  factory: "CB4SVAWJA6TSRNOJZ7W2AWFW46D5VR4ZMFZKDIKXEINZCZEGZCJZCKMI",
  multihop: "CCLZRD4E72T7JCZCN3P7KNPYNXFYKQCL64ECLX7WP5GNVYPYJGU2IO2G",
  phoToken: "CBZ7M5B3Y4WWBZ5XK5UZCAFOEZ23KSSZXYECYX3IXM6E2JOLQC52DK32",
  knownPools: [],
};

const TESTNET_DEFINDEX: DefindexContracts = {
  // NOTE: DEFINDEX_FACTORY on testnet is the same as BLEND_V2_POOL_FACTORY (copy-paste error).
  // Do not use the factory for discovery on testnet — use knownVaults instead.
  factory: "CDSCWE4GLNBYYTES2OCYDFQA2LLY4RBIAX6ZI32VSUXD7GO6HRPO4A32",
  knownVaults: [
    { name: "DeFindex USDC Vault", address: "CBMVK2JK6NTOT2O4HNQAIQFJY232BHKGLIMXDVQVHIIZKDACXDFZDWHN", asset: "USDC" },
    { name: "DeFindex XLM Vault",  address: "CCLV4H7WTLJQ7ATLHBBQV2WW3OINF3FOY5XZ7VPHZO7NH3D2ZS4GFSF6", asset: "XLM" },
  ],
};

// ─── Combined network config ──────────────────────────────────────

export interface NetworkContracts {
  tokens: TokenContracts;
  blend: BlendContracts;
  soroswap: SoroswapContracts;
  aquarius: AquariusContracts;
  phoenix: PhoenixContracts;
  defindex: DefindexContracts;
}

export const NETWORK_CONTRACTS: Record<StellarNetwork, NetworkContracts> = {
  mainnet: {
    tokens: MAINNET_TOKENS,
    blend: MAINNET_BLEND,
    soroswap: MAINNET_SOROSWAP,
    aquarius: MAINNET_AQUARIUS,
    phoenix: MAINNET_PHOENIX,
    defindex: MAINNET_DEFINDEX,
  },
  testnet: {
    tokens: TESTNET_TOKENS,
    blend: TESTNET_BLEND,
    soroswap: TESTNET_SOROSWAP,
    aquarius: TESTNET_AQUARIUS,
    phoenix: TESTNET_PHOENIX,
    defindex: TESTNET_DEFINDEX,
  },
};

// ─── Typed accessors ──────────────────────────────────────────────

export function getContracts(network: StellarNetwork): NetworkContracts {
  return NETWORK_CONTRACTS[network];
}

export function getTokenContracts(network: StellarNetwork): TokenContracts {
  return NETWORK_CONTRACTS[network].tokens;
}

export function getBlendContracts(network: StellarNetwork): BlendContracts {
  return NETWORK_CONTRACTS[network].blend;
}

export function getSoroswapContracts(network: StellarNetwork): SoroswapContracts {
  return NETWORK_CONTRACTS[network].soroswap;
}

export function getAquariusContracts(network: StellarNetwork): AquariusContracts {
  return NETWORK_CONTRACTS[network].aquarius;
}

export function getPhoenixContracts(network: StellarNetwork): PhoenixContracts {
  return NETWORK_CONTRACTS[network].phoenix;
}

export function getDefindexContracts(network: StellarNetwork): DefindexContracts {
  return NETWORK_CONTRACTS[network].defindex;
}

// ─── Legacy: flat KNOWN_CONTRACTS for backward compat ────────────
// Used by mcp-stellar code that reads KNOWN_CONTRACTS[network].BLEND_V2_BACKSTOP etc.
// Gradually migrate callers to the typed accessors above.

export const KNOWN_CONTRACTS: Record<StellarNetwork, Record<string, unknown>> = {
  mainnet: {
    USDC: MAINNET_TOKENS.usdc,
    XLM_SAC: MAINNET_TOKENS.xlmSac,
    XLM_SAC_SOROSWAP: MAINNET_TOKENS.xlmSacSoroswap,
    SOROSWAP_ROUTER: MAINNET_SOROSWAP.router,
    DEFINDEX_FACTORY: MAINNET_DEFINDEX.factory,
    BLEND_V2_BACKSTOP: MAINNET_BLEND.backstop,
    BLEND_V2_POOL_FACTORY: MAINNET_BLEND.poolFactory,
    BLEND_EMITTER: MAINNET_BLEND.emitter,
    BLND_TOKEN: MAINNET_BLEND.blndToken,
    BLEND_V2_POOLS: MAINNET_BLEND.knownPools,
    BLEND_COMET_LP_POOL: MAINNET_BLEND.cometLpPool,
    BLEND_COMET_FACTORY: MAINNET_BLEND.cometFactory,
    AQUARIUS_ROUTER: MAINNET_AQUARIUS.router,
    AQUA_TOKEN: MAINNET_AQUARIUS.aquaToken,
    PHOENIX_FACTORY: MAINNET_PHOENIX.factory,
    PHOENIX_MULTIHOP: MAINNET_PHOENIX.multihop,
    PHO_TOKEN: MAINNET_PHOENIX.phoToken,
  },
  testnet: {
    USDC: TESTNET_TOKENS.usdc,
    XLM_SAC: TESTNET_TOKENS.xlmSac,
    BLND: TESTNET_BLEND.blndToken,
    SOROSWAP_ROUTER: TESTNET_SOROSWAP.router,
    SOROSWAP_FACTORY: TESTNET_SOROSWAP.factory,
    BLEND_POOL: TESTNET_BLEND.knownPools[0]?.address ?? "",
    BLEND_BACKSTOP: TESTNET_BLEND.backstop,
    BLEND_V2_BACKSTOP: TESTNET_BLEND.backstop,
    BLEND_V2_POOL_FACTORY: TESTNET_BLEND.poolFactory,
    BLEND_EMITTER: TESTNET_BLEND.emitter,
    BLND_TOKEN: TESTNET_BLEND.blndToken,
    BLEND_V2_POOLS: TESTNET_BLEND.knownPools,
    BLEND_COMET_LP_POOL: TESTNET_BLEND.cometLpPool,
    BLEND_COMET_FACTORY: TESTNET_BLEND.cometFactory,
    DEFINDEX_FACTORY: TESTNET_DEFINDEX.factory,
    DEFINDEX_KNOWN_VAULTS: TESTNET_DEFINDEX.knownVaults ?? [],
    AQUARIUS_ROUTER: TESTNET_AQUARIUS.router,
    AQUA_TOKEN: TESTNET_AQUARIUS.aquaToken,
    PHOENIX_FACTORY: TESTNET_PHOENIX.factory,
    PHOENIX_MULTIHOP: TESTNET_PHOENIX.multihop,
    PHO_TOKEN: TESTNET_PHOENIX.phoToken,
  },
};

// ─── Known Assets ─────────────────────────────────────────────────

export const KNOWN_ASSETS: Record<
  StellarNetwork,
  Record<string, { classic: string; contract: string }>
> = {
  mainnet: {
    XLM: {
      classic: "XLM",
      contract: MAINNET_TOKENS.xlmSacSoroswap,
    },
    USDC: {
      classic: "USDC:GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
      contract: MAINNET_TOKENS.usdc,
    },
    PHO: {
      classic: "PHO:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: MAINNET_PHOENIX.phoToken,
    },
    BLND: {
      classic: "BLND:GDJEHTBE6ZHUXSWFI642DCGLUOECLHPF3KSXHPXTSTJ7E3JF6MQ5EZYY",
      contract: MAINNET_BLEND.blndToken,
    },
    AQUA: {
      classic: "AQUA:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: MAINNET_AQUARIUS.aquaToken,
    },
    EURC: {
      classic: "EURC:GDHU6WRG4IEQXM5NZ4BMPKOXHW76MZM4Y2IEMFDVXBSDP6SJY4ITNPP2",
      contract: "CDTKPWPLOURQA2SGTKTUQOWRCBZEORB4BWBOMJ3D3ZTQQSGE5F6JBQLV",
    },
    CETES: {
      classic: "CETES:GCRYUGD5NVARGXT56XEZI5CIFCQETYHAPQQTHO2O3IQZTHDH4LATMYWC",
      contract: "CAL6ER2TI6CTRAY6BFXWNWA7WTYXUXTQCHUBCIBU5O6KM3HJFG6Z6VXV",
    },
    USTRY: {
      classic: "USTRY:GCRYUGD5NVARGXT56XEZI5CIFCQETYHAPQQTHO2O3IQZTHDH4LATMYWC",
      contract: "CBLV4ATSIWU67CFSQU2NVRKINQIKUZ2ODSZBUJTJ43VJVRSBTZYOPNUR",
    },
    TESOURO: {
      classic: "TESOURO:GCRYUGD5NVARGXT56XEZI5CIFCQETYHAPQQTHO2O3IQZTHDH4LATMYWC",
      contract: "CD6M4R2322BYCY2LNWM74PEBQAQ63SA3DUJLI3L4225U4ZVCLMSCBCIS",
    },
    USDx: {
      classic: "USDx:GAVH5ZWACAY2PHPUG4FL3LHHJIYIHOFPSIUGM2KHK25CJWXHAV6QKDMN",
      contract: "CDIKURWHYS4FFTR5KOQK6MBFZA2K3E26WGBQI6PXBYWZ4XIOPJHDFJKP",
    },
    EURx: {
      classic: "EURx:GAVH5ZWACAY2PHPUG4FL3LHHJIYIHOFPSIUGM2KHK25CJWXHAV6QKDMN",
      contract: "CBN3NCJSMOQTC6SPEYK3A44NU4VS3IPKTARJLI3Y77OH27EWBY36TP7U",
    },
    GBPx: {
      classic: "GBPx:GAVH5ZWACAY2PHPUG4FL3LHHJIYIHOFPSIUGM2KHK25CJWXHAV6QKDMN",
      contract: "CBCO65UOWXY2GR66GOCMCN6IU3Y45TXCPBY3FLUNL4AOUMOCKVIVV6JC",
    },
    oUSD: {
      classic: "oUSD:GBIWJGAOSFC4KUPHXM573TKTWHMI7VW7D4GCHYZYH243Q6HVBV7ORBIT",
      contract: "CBZPEXQLJCGUYTAQRQ4FGCXUV5O4TZER5WSOMCGNDNIIO4EJ4FU5GQNZ",
    },
    USDGLO: {
      classic: "USDGLO:GBBS25EGYQPGEZCGCFBKG4OAGFXU6DSOQBGTHELLJT3HZXZJ34HWS6XV",
      contract: "CB226ZOEYXTBPD3QEGABTJYSKZVBP2PASEISLG3SBMTN5CE4QZUVZ3CE",
    },
    PYUSD: {
      classic: "PYUSD:GDQE7IXJ4HUHV6RQHIUPRJSEZE4DRS5WY577O2FY6YQ5LVWZ7JZTU2V5",
      contract: "CCCRWH6Q3FNP3I2I57BDLM5AFAT7O6OF6GKQOC6SSJNDAVRZ57SPHGU2",
    },
    // ── Aquarius pooled tokens (mainnet) ──────────────────────
    RLUSD: {
      classic: "RLUSD:GAYHAAKPAQLTRLN4D4F3DKIZ3RMQBQWBYD7XSLZS3DHQOAConv5YZXOR",
      contract: "CACOHEZ4V5SCZSQWUNHVRGEYRNF7KSTQIKAZY3KSI6C4MC5KSXMX7Z7W",
    },
    yVELO: {
      classic: "yVELO:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CADUFDKX5B7WQN4HJLW4DZD5C737QSRS2X4PBVX3NFBZPULQYU4LRE3P",
    },
    xSolvBTC: {
      classic: "xSolvBTC:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CAUP7NFABXE5TJRL3FKTPMWRLC7IAXYDCTHQRFSCLR5TMGKHOOQO772J",
    },
    SolvBTC: {
      classic: "SolvBTC:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CBIJBDNZNF4X35BJ4FFZWCDBSCKOP5NB4PLG4SNENRMLAPYG4P5FM6VN",
    },
    bEURC: {
      classic: "bEURC:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CAZ6ISXEH5EZROKBAAPZO6C55ZILT5QYPNTAT7P4JN2OFWIHSLHEHDMR",
    },
    bUSDC: {
      classic: "bUSDC:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CBWNWMD2XSJFQFAU5V3J3VJ7R2DZLLKB4SLIV6RPEBIO26IIJPCLHSTF",
    },
    apUSDC: {
      classic: "apUSDC:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CB7VCORLWN5N4ZUTKSK7OQN6JC5ENKBK6NSKUZDEEPFMJGMH3U6AAIK4",
    },
    abUSDC: {
      classic: "abUSDC:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CBNJ54GNIRXBRB2P7PVKI7LVUBVR4ATTK6QDPZZKHM47VAP3CSJ7VYNB",
    },
    KRWC: {
      classic: "KRWC:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CAB7CSQK7TNVYGVMYEMOAPM56S6WZSZD3MPJCZ5KFPCUVQ4X2VLQOQDT",
    },
    GBPC: {
      classic: "GBPC:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CCHBWUYVW4QAXQ2KVKSCXT37SWLQOCTAYG2QRQDMLAZXVJJPUO2ZAGXS",
    },
    AUD: {
      classic: "AUD:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CBUJ6F5SPBPFGGTLO4FTD6IMRX5PDEMAEFX7WNPEWGRYMHOQNDJ6J44Y",
    },
    USDM: {
      classic: "USDM:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CDKLJRIL7E2OWHTPTIHCAXTXI6PEXFOS6PJFAFCDBYWDT3B3QI42EOJA",
    },
    ZUSD: {
      classic: "ZUSD:GDF6VOEGRWLOZ64PQQGKD2IYWA22RLT37GJKS2EJXZHT2VLAGWLC5TOB",
      contract: "CDANHN6OUDZNFWDCEU6ZWCIC4DPHVFXP3QPARHALFOF26HLC45JWRTWP",
    },
    EURMTL: {
      classic: "EURMTL:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CDUYP3U6HGTOBUNQD2WTLWNMNADWMENROKZZIHGEVGKIU3ZUDF42CDOK",
    },
    LBTC: {
      classic: "LBTC:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CDWGJD5R37BQIU23LBNUQXIW45WS3CIJPJSP3I4FG5OYDX5MZDTP2RZ6",
    },
    SUI: {
      classic: "SUI:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CAXNFHKKINQMYMOJ7IARH2AU3HVDZJAD7JG75FC7XCMIK36JQXZIFLEV",
    },
    TON: {
      classic: "TON:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CCXMZ44BJQOQAUZCOJQHBVYLPJCNSE7TOFRYYRUIXA2CPTNP5NOQO2YN",
    },
    XAG: {
      classic: "XAG:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CBUVZ2BNKZZVMCZEXFHBUREZQBJPQHJJ3TBW7SWF37QAIZ3YZCZAAVXA",
    },
    GOLD: {
      classic: "GOLD:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CCDCWXSE7WKZSZGIMBNHRM5A4OJJ5KQNF2SLJA4UHBNPETA4E6FD6MD7",
    },
    PALL: {
      classic: "PALL:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CANMX45P3KM52P4LKX242FBKL5B7XRYHLRO4XKEVSGCT6ZHLST4Q7HCD",
    },
    SLVR: {
      classic: "SLVR:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CBNWETETHVP4XVD7FSCEQPWHPX32YTARIKRQKXRW26ATEBCAUXLVUU4I",
    },
    COPR: {
      classic: "COPR:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CCOUZFF7W326VYNONSSDF7LDLEIAUMYAMLYZDMFAJLXDN3TTZWR6HHWI",
    },
    ZINC: {
      classic: "ZINC:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CD3O7FMUWRTWCBYJ3AHVVSPLVBS3BBFLYD4PR52GQHZ6R5WBNCW7EFBK",
    },
    XRF: {
      classic: "XRF:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CBLLEW7HD2RWATVSMLAGWM4G3WCHSHDJ25ALP4DI6LULV5TU35N2CIZA",
    },
    NGNC: {
      classic: "NGNC:GASBV6W7GGED66MXEVC7YZHTWWYMSVYEY35USF2HJZBLABLYIFQGXZY6",
      contract: "CBYFV4W2LTMXYZ3XWFX5BK2BY255DU2DSXNAE4FJ5A5VYUWGIBJDOIGG",
    },
    LSP: {
      classic: "LSP:GAB7STHVD5BDH3EEYXPI3OM7PCS4V443PYB5FNT6CFGJVPDLMKDM24WK",
      contract: "CBXE6V454EUYWVQCI4TCSOG4CSNPQ2BLYOTKAKXYFHO3KNVX4CXYCY2T",
    },
    SSLX: {
      classic: "SSLX:GBHFGY3ZNEJWLNO4LBUKLYOCEK4V7ENEBJGPRHHX7JU47GWHBREH37UR",
      contract: "CBHBD77PWZ3AXPQVYVDBHDKEMVNOR26UZUZHWCB6QC7J5SETQPRUQAS4",
    },
    AFR: {
      classic: "AFR:GBX6YI45VU7WNAAKA3RBFDR3I3UKNFHTJPQ5F6KOOKSGYIAM4TRQN54W",
      contract: "CCG27OZ5AV4WUXS6XTECWAXEY5UOMEFI2CWFA3LHZGBTLYZWTJF3MJYQ",
    },
    CARBON: {
      classic: "CARBON:GCBOATLWKXACOWKRRWORARDI2HFDSYPALMTS23YBZKHOB6XLW6CARBON",
      contract: "CDDS7IQJGQ2ZMO66E3MUYXZ56H2OO7RBTTAGZLZKOEA4EXCGZX65JGA7",
    },
    SHX: {
      classic: "SHX:GDSTRSHXHGJ7ZIVRBXEYE5Q74XUVCUSEKEBR7UCHEUUEK72N7I7KJ6JH",
      contract: "CCKCKCPHYVXQD4NECBFJTFSCU2AMSJGCNG4O6K4JVRE2BLPR7WNDBQIQ",
    },
    KALE: {
      classic: "KALE:GBDVX4VELCDSQ54KQJYTNHXAHFLBCA77ZY2USQBM4CSHTTV7DME7KALE",
      contract: "CB23WRDQWGSP6YPMY4UV5C4OW5CBTXKYN3XEATG7KJEZCXMJBYEHOUOV",
    },
    USDY: {
      classic: "USDY:GAJMPX5NBOG6TQFPQGRABJEEB2YE7RFRLUKJDZAZGAD5GFX4J7TADAZ6",
      contract: "CB3YA656OYIHU57657I5KGSBRHE5I3OZU4VFC22PYAOANFZHEWNYGAGP",
    },
    yBTC: {
      classic: "yBTC:GBUVRNH4RW4VLHP4C5MOF46RRIRZLAVHYGX45MVSTKA2F6TMR7E7L6NW",
      contract: "CB2XMFB6BDIHFOSFB5IXHDOYV3SI3IXMNIZLPDZHC7ENDCXSBEBZAO2Y",
    },
    yETH: {
      classic: "yETH:GDYQNEF2UWTK4L6HITMT53MZ6F5QWO3Q4UVE6SCGC4OMEQIZQQDERQFD",
      contract: "CDYEOOVL6WV4JRY45CXQKOBJFFAPOM5KNQCCDNM333L6RM2L4RO3LKYG",
    },
    yUSDC: {
      classic: "yUSDC:GDGTVWSM4MGS4T7Z6W4RPWOCHE2I6RDFCIFZGS3DOA63LWQTRNZNTTFF",
      contract: "CDOFW7HNKLUZRLFZST4EW7V3AV4JI5IHMT6BPXXSY2IEFZ4NE5TWU2P4",
    },
    yXLM: {
      classic: "yXLM:GARDNV3Q7YGT4AKSDF25LT32YSCCW4EV22Y2TV3I2PU2MMXJTEDL5T55",
      contract: "CBZVSNVB55ANF24QVJL2K5QCLOAB6XITGTGXYEAF6NPTXYKEJUYQOHFC",
    },
  },
  testnet: {
    XLM: {
      classic: "XLM",
      contract: TESTNET_TOKENS.xlmSac,
    },
    USDC: {
      // Testnet USDC with actual Aquarius/SDEX liquidity (issuer GAHPYWLK...)
      classic: "USDC:GAHPYWLK6YRN7CVYZOO4H3VDRZ7PVF5UJGLZCSPAEIKJE2XSWF5LAGER",
      contract: TESTNET_TOKENS.usdc,
    },
    USDT: {
      classic: "USDT:GAHPYWLK6YRN7CVYZOO4H3VDRZ7PVF5UJGLZCSPAEIKJE2XSWF5LAGER",
      contract: "CBL6KD2LFMLAUKFFWNNXWOXFN73GAXLEA4WMJRLQ5L76DMYTM3KWQVJN",
    },
    BLND: {
      classic: "BLND:GDJEHTBE6ZHUXSWFI642DCGLUOECLHPF3KSXHPXTSTJ7E3JF6MQ5EZYY",
      contract: TESTNET_BLEND.blndToken,
    },
    AQUA: {
      classic: "AQUA:GAHPYWLK6YRN7CVYZOO4H3VDRZ7PVF5UJGLZCSPAEIKJE2XSWF5LAGER",
      contract: "CDNVQW44C3HALYNVQ4SOBXY5EWYTGVYXX6JPESOLQDABJI5FC5LTRRUE",
    },
    ETH: {
      classic: "ETH:GAHPYWLK6YRN7CVYZOO4H3VDRZ7PVF5UJGLZCSPAEIKJE2XSWF5LAGER",
      contract: "CC5NJ2JSJF3DDTFW5X4PZHZF2F7YCVDLVM76ZYPR5RTTNB7QNAT7KRWR",
    },
    BTC: {
      classic: "BTC:GAHPYWLK6YRN7CVYZOO4H3VDRZ7PVF5UJGLZCSPAEIKJE2XSWF5LAGER",
      contract: "CBSXOAE7GAW7Y3CHTNZ3D4GLB6KI43MC36DY7GTZN4AGI7AWQ5V55YIQ",
    },
    DAI: {
      classic: "DAI:GAHPYWLK6YRN7CVYZOO4H3VDRZ7PVF5UJGLZCSPAEIKJE2XSWF5LAGER",
      contract: "CDWURCDIASTOAIUKRETTTVGUCIHCUJTIK6QGDJKOW4QSID6VYGXOMGKM",
    },
    ICE: {
      classic: "ICE:GAHPYWLK6YRN7CVYZOO4H3VDRZ7PVF5UJGLZCSPAEIKJE2XSWF5LAGER",
      contract: "CCQZWA6GDCNLEMNUYTCMYGIXLX3ECAXW7RICSUZWWXM5AMDWAANC4SZK",
    },
    PHO: {
      classic: "PHO:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      contract: "CBZ7M5B3Y4WWBZ5XK5UZCAFOEZ23KSSZXYECYX3IXM6E2JOLQC52DK32",
    },
    CETES: {
      classic: "CETES:GCRYUGD5NVARGXT56XEZI5CIFCQETYHAPQQTHO2O3IQZTHDH4LATMYWC",
      contract: "CC72F57YTPX76HAA64JQOEGHQAPSADQWSY5DWVBR66JINPFDLNCQYHIC",
    },
    WETH: {
      classic: "wETH:GAHPYWLK6YRN7CVYZOO4H3VDRZ7PVF5UJGLZCSPAEIKJE2XSWF5LAGER",
      contract: "CAZAQB3D7KSLSNOSQKYD2V4JP5V2Y3B4RDJZRLBFCCIXDCTE3WHSY3UE",
    },
    WBTC: {
      classic: "WBTC:GAHPYWLK6YRN7CVYZOO4H3VDRZ7PVF5UJGLZCSPAEIKJE2XSWF5LAGER",
      contract: "CAP5AMC2OHNVREO66DFIN6DHJMPOBAJ2KCDDIMFBR7WWJH5RZBFM3UEI",
    },
  },
};

export const NATIVE_ASSET_CODE = "XLM";
export const NATIVE_ASSET_ISSUER = "native";

// ─── Legacy helpers (for backward compat) ────────────────────────

/** @deprecated Use getContracts(network).tokens instead */
export function getKnownContracts(network: StellarNetwork): Record<string, unknown> {
  return KNOWN_CONTRACTS[network];
}

export function getKnownAssets(
  network: StellarNetwork,
): Record<string, { classic: string; contract: string }> {
  return KNOWN_ASSETS[network];
}

export function getXlmSac(network: StellarNetwork): string {
  return NETWORK_CONTRACTS[network].tokens.xlmSacSoroswap;
}

export function getBlendV2Backstop(network: StellarNetwork): string {
  return NETWORK_CONTRACTS[network].blend.backstop;
}

export function getBlendV2Pools(
  network: StellarNetwork,
): ReadonlyArray<{ name: string; address: string }> {
  return NETWORK_CONTRACTS[network].blend.knownPools;
}
