/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AccountControllerBuildRevokeTx201 {
}

export interface AccountControllerBuildRevokeTxMutationRequest {
}

export interface AccountControllerBuildRevokeTxMutationResponse {
}

export interface AccountControllerBuildRevokeTxMutation {
}