/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AccountControllerBuildDeployTx201 {
}

export interface AccountControllerBuildDeployTxMutationRequest {
}

export interface AccountControllerBuildDeployTxMutationResponse {
}

export interface AccountControllerBuildDeployTxMutation {
}