/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AccountControllerBuildWithdrawTx201 {
}

export interface AccountControllerBuildWithdrawTxMutationRequest {
}

export interface AccountControllerBuildWithdrawTxMutationResponse {
}

export interface AccountControllerBuildWithdrawTxMutation {
}