/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AccountControllerGetActivityPathParams {
  publicKey: string
}

export interface AccountControllerGetActivityQueryParams {
  limit: string
}

export interface AccountControllerGetActivity200 {
}

export interface AccountControllerGetActivityQueryResponse {
}

export interface AccountControllerGetActivityQuery {
}