/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AccountControllerBuildFundTx201 {
}

export interface AccountControllerBuildFundTxMutationRequest {
}

export interface AccountControllerBuildFundTxMutationResponse {
}

export interface AccountControllerBuildFundTxMutation {
}