/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AccountControllerSubmitTx201 {
}

export interface AccountControllerSubmitTxMutationRequest {
}

export interface AccountControllerSubmitTxMutationResponse {
}

export interface AccountControllerSubmitTxMutation {
}