/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AccountControllerUpdatePresetPathParams {
  publicKey: string
}

export interface AccountControllerUpdatePreset200 {
}

export interface AccountControllerUpdatePresetMutationRequest {
}

export interface AccountControllerUpdatePresetMutationResponse {
}

export interface AccountControllerUpdatePresetMutation {
}