/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AccountControllerBuildSetupTxs201 {
}

export interface AccountControllerBuildSetupTxsMutationRequest {
}

export interface AccountControllerBuildSetupTxsMutationResponse {
}

export interface AccountControllerBuildSetupTxsMutation {
}