/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AccountControllerResumeAccountPathParams {
  publicKey: string
}

export interface AccountControllerResumeAccount201 {
}

export interface AccountControllerResumeAccountMutationResponse {
}

export interface AccountControllerResumeAccountMutation {
}