/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AccountControllerGetPositionPathParams {
  publicKey: string
}

export interface AccountControllerGetPosition200 {
}

export interface AccountControllerGetPositionQueryResponse {
}

export interface AccountControllerGetPositionQuery {
}