/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AdminControllerGetDashboard200 {
}

export interface AdminControllerGetDashboardQueryResponse {
}

export interface AdminControllerGetDashboardQuery {
}