/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AdminControllerListCampaigns200 {
}

export interface AdminControllerListCampaignsQueryResponse {
}

export interface AdminControllerListCampaignsQuery {
}