/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AdminControllerRevokeCodePathParams {
  id: string
}

export interface AdminControllerRevokeCode200 {
}

export interface AdminControllerRevokeCodeMutationResponse {
}

export interface AdminControllerRevokeCodeMutation {
}