/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AdminAuthControllerLogin200 {
}

export interface AdminAuthControllerLoginMutationRequest {
}

export interface AdminAuthControllerLoginMutationResponse {
}

export interface AdminAuthControllerLoginMutation {
}