/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AdminAuthControllerCreateAdmin201 {
}

export interface AdminAuthControllerCreateAdminMutationRequest {
}

export interface AdminAuthControllerCreateAdminMutationResponse {
}

export interface AdminAuthControllerCreateAdminMutation {
}