/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AdminControllerGetRegistrationStatsQueryParams {
  days?: number
}

export interface AdminControllerGetRegistrationStats200 {
}

export interface AdminControllerGetRegistrationStatsQueryResponse {
}

export interface AdminControllerGetRegistrationStatsQuery {
}