/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AdminControllerGetCampaignStatusPathParams {
  id: string
}

export interface AdminControllerGetCampaignStatus200 {
}

export interface AdminControllerGetCampaignStatusQueryResponse {
}

export interface AdminControllerGetCampaignStatusQuery {
}