/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AdminControllerSendCampaign201 {
}

export interface AdminControllerSendCampaignMutationRequest {
}

export interface AdminControllerSendCampaignMutationResponse {
}

export interface AdminControllerSendCampaignMutation {
}