/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AdminControllerListCodesQueryParams {
  page?: number
}

export interface AdminControllerListCodes200 {
}

export interface AdminControllerListCodesQueryResponse {
}

export interface AdminControllerListCodesQuery {
}