/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AdminControllerGenerateCodes201 {
}

export interface AdminControllerGenerateCodesMutationRequest {
}

export interface AdminControllerGenerateCodesMutationResponse {
}

export interface AdminControllerGenerateCodesMutation {
}