/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AuthControllerRegister201 {
}

export interface AuthControllerRegisterMutationResponse {
}

export interface AuthControllerRegisterMutation {
}