/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AuthControllerChallenge201 {
}

export interface AuthControllerChallengeMutationRequest {
}

export interface AuthControllerChallengeMutationResponse {
}

export interface AuthControllerChallengeMutation {
}