/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AuthControllerVerify201 {
}

export interface AuthControllerVerifyMutationRequest {
}

export interface AuthControllerVerifyMutationResponse {
}

export interface AuthControllerVerifyMutation {
}