/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AuthControllerLogin201 {
}

export interface AuthControllerLoginMutationRequest {
}

export interface AuthControllerLoginMutationResponse {
}

export interface AuthControllerLoginMutation {
}