/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface EmailControllerSendTestEmail200 {
}

export interface EmailControllerSendTestEmailMutationResponse {
}

export interface EmailControllerSendTestEmailMutation {
}