/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface HealthControllerCheck200 {
}

export interface HealthControllerCheckQueryResponse {
}

export interface HealthControllerCheckQuery {
}