/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


;

export interface PoolsControllerGetPoolsQueryParamsRiskPresetEnumKey {
}

export interface PoolsControllerGetPoolsQueryParams {
  baseAsset?: string
  riskPreset?: "SAFE" | "BALANCED" | "AGGRESSIVE"
}

export interface PoolsControllerGetPools200 {
}

export interface PoolsControllerGetPoolsQueryResponse {
}

export interface PoolsControllerGetPoolsQuery {
}