/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface PoolsControllerGetPoolHistoryPathParams {
  id: string
}

export interface PoolsControllerGetPoolHistory200 {
}

export interface PoolsControllerGetPoolHistoryQueryResponse {
}

export interface PoolsControllerGetPoolHistoryQuery {
}