/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Returns list of all supported protocols
*/
export interface ProtocolControllerGetAllProtocols200 {
}

export interface ProtocolControllerGetAllProtocolsQueryResponse {
}

export interface ProtocolControllerGetAllProtocolsQuery {
}