/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


;

export interface ProtocolControllerGetLendingApyQueryParamsProtocolEnumKey {
}

;

export interface ProtocolControllerGetLendingApyQueryParamsChainEnumKey {
}

export interface ProtocolControllerGetLendingApyQueryParams {
  protocol: "aave" | "spark" | "compound" | "moonwell" | "fluid" | "euler" | "harvest" | "wasabi" | "morpho" | "silo" | "dolomite"
  chain: "base" | "arbitrum" | "sonic" | "plasma"
  asset: string
}

/**
 * @description Returns the supply APY for the specified protocol and asset
*/
export interface ProtocolControllerGetLendingApy200 {
}

export interface ProtocolControllerGetLendingApyQueryResponse {
}

export interface ProtocolControllerGetLendingApyQuery {
}