/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface ProtocolControllerGetAvailableAssetsQueryParams {
  chain: string
}

/**
 * @description Returns list of available assets on the specified chain
*/
export interface ProtocolControllerGetAvailableAssets200 {
}

export interface ProtocolControllerGetAvailableAssetsQueryResponse {
}

export interface ProtocolControllerGetAvailableAssetsQuery {
}