/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


;

export interface ProtocolControllerGetUserPositionQueryParamsProtocolEnumKey {
}

export interface ProtocolControllerGetUserPositionQueryParams {
  protocol: "aave" | "spark" | "compound" | "moonwell" | "fluid" | "euler" | "harvest" | "wasabi" | "morpho" | "silo" | "dolomite"
  userAddress: string
  asset?: string
}

/**
 * @description Returns the user supplied position in the protocol
*/
export interface ProtocolControllerGetUserPosition200 {
}

export interface ProtocolControllerGetUserPositionQueryResponse {
}

export interface ProtocolControllerGetUserPositionQuery {
}