/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface ProtocolControllerGetApyByChainQueryParams {
  chain: string
  asset: string
}

/**
 * @description Returns APY from all protocols on the specified chain for an asset
*/
export interface ProtocolControllerGetApyByChain200 {
}

export interface ProtocolControllerGetApyByChainQueryResponse {
}

export interface ProtocolControllerGetApyByChainQuery {
}