/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface RebalanceControllerHalt201 {
}

export interface RebalanceControllerHaltMutationResponse {
}

export interface RebalanceControllerHaltMutation {
}