/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface RebalanceControllerRunHarvestManual201 {
}

export interface RebalanceControllerRunHarvestManualMutationResponse {
}

export interface RebalanceControllerRunHarvestManualMutation {
}