/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface RebalanceControllerResume201 {
}

export interface RebalanceControllerResumeMutationResponse {
}

export interface RebalanceControllerResumeMutation {
}