/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface RebalanceControllerRunManual201 {
}

export interface RebalanceControllerRunManualMutationResponse {
}

export interface RebalanceControllerRunManualMutation {
}