/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface RebalanceControllerGetStatus200 {
}

export interface RebalanceControllerGetStatusQueryResponse {
}

export interface RebalanceControllerGetStatusQuery {
}