/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface UserControllerGetUserPathParams {
  id: string
}

export interface UserControllerGetUser200 {
}

export interface UserControllerGetUserQueryResponse {
}

export interface UserControllerGetUserQuery {
}