/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface WaitlistControllerAttachContact200 {
}

export interface WaitlistControllerAttachContactMutationRequest {
}

export interface WaitlistControllerAttachContactMutationResponse {
}

export interface WaitlistControllerAttachContactMutation {
}