/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface WaitlistControllerRegisterWallet200 {
}

export interface WaitlistControllerRegisterWalletMutationRequest {
}

export interface WaitlistControllerRegisterWalletMutationResponse {
}

export interface WaitlistControllerRegisterWalletMutation {
}