/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface WaitlistControllerRequestChallenge200 {
}

export interface WaitlistControllerRequestChallengeMutationRequest {
}

export interface WaitlistControllerRequestChallengeMutationResponse {
}

export interface WaitlistControllerRequestChallengeMutation {
}