/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface WaitlistControllerRegister200 {
}

export interface WaitlistControllerRegisterMutationRequest {
}

export interface WaitlistControllerRegisterMutationResponse {
}

export interface WaitlistControllerRegisterMutation {
}