/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface WaitlistControllerVerifyReferralQueryParams {
  code: string
}

export interface WaitlistControllerVerifyReferral200 {
}

export interface WaitlistControllerVerifyReferralQueryResponse {
}

export interface WaitlistControllerVerifyReferralQuery {
}