/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface WaitlistControllerGetStatusQueryParams {
  walletAddress: string
}

export interface WaitlistControllerGetStatus200 {
}

export interface WaitlistControllerGetStatusQueryResponse {
}

export interface WaitlistControllerGetStatusQuery {
}