/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from "@/gen-ai/types/error-response";
import type { Thread } from "@/gen-ai/types/thread";
import type { ThreadCreate } from "@/gen-ai/types/thread-create";

/**
 * @description Success
 */
export type CreateThreadThreadsPost200 = Thread;

/**
 * @description Conflict
 */
export type CreateThreadThreadsPost409 = ErrorResponse;

/**
 * @description Validation Error
 */
export type CreateThreadThreadsPost422 = ErrorResponse;

export type CreateThreadThreadsPostMutationRequest = ThreadCreate;

export type CreateThreadThreadsPostMutationResponse = CreateThreadThreadsPost200;

export type CreateThreadThreadsPostMutation = {
  Response: CreateThreadThreadsPost200;
  Request: CreateThreadThreadsPostMutationRequest;
  Errors: CreateThreadThreadsPost409 | CreateThreadThreadsPost422;
};
