/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Assistant } from "@/gen-ai/types/assistant";
import type { AssistantCreate } from "@/gen-ai/types/assistant-create";
import type { ErrorResponse } from "@/gen-ai/types/error-response";

/**
 * @description Success
 */
export type CreateAssistantAssistantsPost200 = Assistant;

/**
 * @description Not Found
 */
export type CreateAssistantAssistantsPost404 = ErrorResponse;

/**
 * @description Conflict
 */
export type CreateAssistantAssistantsPost409 = ErrorResponse;

/**
 * @description Validation Error
 */
export type CreateAssistantAssistantsPost422 = ErrorResponse;

export type CreateAssistantAssistantsPostMutationRequest = AssistantCreate;

export type CreateAssistantAssistantsPostMutationResponse = CreateAssistantAssistantsPost200;

export type CreateAssistantAssistantsPostMutation = {
  Response: CreateAssistantAssistantsPost200;
  Request: CreateAssistantAssistantsPostMutationRequest;
  Errors:
    | CreateAssistantAssistantsPost404
    | CreateAssistantAssistantsPost409
    | CreateAssistantAssistantsPost422;
};
