/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ListNamespaceResponse } from "@/gen-ai/types/list-namespace-response";

export type ListNamespacesResponse = ListNamespaceResponse;
