/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RunCreateStateless } from "@/gen-ai/types/run-create-stateless";

/**
 * @description Payload for creating a batch of runs.
 */
export type RunBatchCreate = RunCreateStateless[];
