/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Cron } from "@/gen-ai/types/cron";
import type { CronSearch } from "@/gen-ai/types/cron-search";
import type { ErrorResponse } from "@/gen-ai/types/error-response";

/**
 * @description Success
 */
export type SearchCronsRunsCronsPost200 = Cron[];

/**
 * @description Validation Error
 */
export type SearchCronsRunsCronsPost422 = ErrorResponse;

export type SearchCronsRunsCronsPostMutationRequest = CronSearch;

export type SearchCronsRunsCronsPostMutationResponse = SearchCronsRunsCronsPost200;

export type SearchCronsRunsCronsPostMutation = {
  Response: SearchCronsRunsCronsPost200;
  Request: SearchCronsRunsCronsPostMutationRequest;
  Errors: SearchCronsRunsCronsPost422;
};
