/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ProtocolControllerGetAvailableAssetsQueryResponse, ProtocolControllerGetAvailableAssetsQueryParams } from "@/gen-backend/types/protocol-controller-get-available-assets";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { protocolControllerGetAvailableAssets } from "@/gen-backend/client/protocol-controller-get-available-assets";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const protocolControllerGetAvailableAssetsSuspenseQueryKey = (params: ProtocolControllerGetAvailableAssetsQueryParams) => [{ url: '/api/protocol/assets' }, ...(params ? [params] : [])] as const

export type ProtocolControllerGetAvailableAssetsSuspenseQueryKey = ReturnType<typeof protocolControllerGetAvailableAssetsSuspenseQueryKey>

export function protocolControllerGetAvailableAssetsSuspenseQueryOptions(params: ProtocolControllerGetAvailableAssetsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = protocolControllerGetAvailableAssetsSuspenseQueryKey(params)
  return queryOptions<ProtocolControllerGetAvailableAssetsQueryResponse, ResponseErrorConfig<Error>, ProtocolControllerGetAvailableAssetsQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return protocolControllerGetAvailableAssets(params, config)
   },
  })
}

/**
 * @summary Get available assets for a chain
 * {@link /api/protocol/assets}
 */
export function useProtocolControllerGetAvailableAssetsSuspense<TData = ProtocolControllerGetAvailableAssetsQueryResponse, TQueryKey extends QueryKey = ProtocolControllerGetAvailableAssetsSuspenseQueryKey>(params: ProtocolControllerGetAvailableAssetsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ProtocolControllerGetAvailableAssetsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? protocolControllerGetAvailableAssetsSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...protocolControllerGetAvailableAssetsSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}