/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AccountControllerGetPresetsQueryResponse } from "@/gen-backend/types/account-controller-get-presets";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { accountControllerGetPresets } from "@/gen-backend/client/account-controller-get-presets";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const accountControllerGetPresetsQueryKey = () => [{ url: '/api/account/presets' }] as const

export type AccountControllerGetPresetsQueryKey = ReturnType<typeof accountControllerGetPresetsQueryKey>

export function accountControllerGetPresetsQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = accountControllerGetPresetsQueryKey()
  return queryOptions<AccountControllerGetPresetsQueryResponse, ResponseErrorConfig<Error>, AccountControllerGetPresetsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return accountControllerGetPresets(config)
   },
  })
}

/**
 * @summary Get preset card data with live APY estimates
 * {@link /api/account/presets}
 */
export function useAccountControllerGetPresets<TData = AccountControllerGetPresetsQueryResponse, TQueryData = AccountControllerGetPresetsQueryResponse, TQueryKey extends QueryKey = AccountControllerGetPresetsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<AccountControllerGetPresetsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? accountControllerGetPresetsQueryKey()

  const query = useQuery({
   ...accountControllerGetPresetsQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}