/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminControllerListCampaignsQueryResponse } from "@/gen-backend/types/admin-controller-list-campaigns";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { adminControllerListCampaigns } from "@/gen-backend/client/admin-controller-list-campaigns";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const adminControllerListCampaignsQueryKey = () => [{ url: '/api/admin/campaigns' }] as const

export type AdminControllerListCampaignsQueryKey = ReturnType<typeof adminControllerListCampaignsQueryKey>

export function adminControllerListCampaignsQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = adminControllerListCampaignsQueryKey()
  return queryOptions<AdminControllerListCampaignsQueryResponse, ResponseErrorConfig<Error>, AdminControllerListCampaignsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return adminControllerListCampaigns(config)
   },
  })
}

/**
 * @summary List all campaign runs ordered by createdAt desc
 * {@link /api/admin/campaigns}
 */
export function useAdminControllerListCampaigns<TData = AdminControllerListCampaignsQueryResponse, TQueryData = AdminControllerListCampaignsQueryResponse, TQueryKey extends QueryKey = AdminControllerListCampaignsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<AdminControllerListCampaignsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? adminControllerListCampaignsQueryKey()

  const query = useQuery({
   ...adminControllerListCampaignsQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}