/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AccountControllerGetPresetsQueryResponse } from "@/gen-backend/types/account-controller-get-presets";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { accountControllerGetPresets } from "@/gen-backend/client/account-controller-get-presets";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const accountControllerGetPresetsSuspenseQueryKey = () => [{ url: '/api/account/presets' }] as const

export type AccountControllerGetPresetsSuspenseQueryKey = ReturnType<typeof accountControllerGetPresetsSuspenseQueryKey>

export function accountControllerGetPresetsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = accountControllerGetPresetsSuspenseQueryKey()
  return queryOptions<AccountControllerGetPresetsQueryResponse, ResponseErrorConfig<Error>, AccountControllerGetPresetsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return accountControllerGetPresets(config)
   },
  })
}

/**
 * @summary Get preset card data with live APY estimates
 * {@link /api/account/presets}
 */
export function useAccountControllerGetPresetsSuspense<TData = AccountControllerGetPresetsQueryResponse, TQueryKey extends QueryKey = AccountControllerGetPresetsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<AccountControllerGetPresetsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? accountControllerGetPresetsSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...accountControllerGetPresetsSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}